### ISSUE TITLE
Review DFD Revision

### ISSUE THREAD

**Issue by g6imxjeo** [UNOmaha-Course-GroupPorjects/ISQA3420#30]
Chris,

See revision on DFD. 
![dfd_v2](https://cloud.githubusercontent.com/assets/14811911/10433125/591f8d7c-70d5-11e5-95d4-d466ebc8ecb1.png)
Please Review as time allows.

Thanks,
Jesse

**Comment by Ashkeelun** [comment]
Reverted Back to use OS CPE Data Flow, I will add CVE separately

Add process to query "National Vulnerability Database" with CPE, to get the CVE.

**Comment by Ashkeelun** [comment]
Completed changes.
Let me know what you think of this.

![image](https://cloud.githubusercontent.com/assets/14626151/10437196/01419746-70f1-11e5-8bca-d66298779c29.png)
