### ISSUE TITLE
Migrate Slides to .md format in Repository

### ISSUE THREAD

**Issue by g6imxjeo** [UNOmaha-Course-GroupPorjects/ISQA3420#57]
Add images of slide deck (currently in google drive) to SlidePresentation.md file.

**Comment by Ashkeelun** [comment]
1
![image](https://cloud.githubusercontent.com/assets/14626151/11705899/91f7beaa-9eb9-11e5-9653-a1a4fb788c02.png)

2
![image](https://cloud.githubusercontent.com/assets/14626151/11705911/a5c978f6-9eb9-11e5-9705-a4d5d3519317.png)

3
![image](https://cloud.githubusercontent.com/assets/14626151/11705919/b70b66ba-9eb9-11e5-9745-e618f6187518.png)

4
![image](https://cloud.githubusercontent.com/assets/14626151/11705924/c8c521f2-9eb9-11e5-8589-92038004cdca.png)

5
![image](https://cloud.githubusercontent.com/assets/14626151/11705928/d7e353d4-9eb9-11e5-8299-ff2f2e6c37fd.png)

6
![image](https://cloud.githubusercontent.com/assets/14626151/11705938/f1c31db6-9eb9-11e5-9066-1e05bc0159ad.png)

7
![image](https://cloud.githubusercontent.com/assets/14626151/11705947/00b2fe86-9eba-11e5-9a80-3953d78d93e3.png)

8
![image](https://cloud.githubusercontent.com/assets/14626151/11705952/0e2deabc-9eba-11e5-9d56-88c4f10c6e02.png)

9
![image](https://cloud.githubusercontent.com/assets/14626151/11705958/1a96a79e-9eba-11e5-8e09-0b1c7d6bfd0e.png)

10
![image](https://cloud.githubusercontent.com/assets/14626151/11705964/2a291d86-9eba-11e5-9100-7aa4870cc05a.png)

11
![image](https://cloud.githubusercontent.com/assets/14626151/11705970/38133832-9eba-11e5-833e-cc2dfa599492.png)

12
![image](https://cloud.githubusercontent.com/assets/14626151/11705981/4b9023f2-9eba-11e5-87e8-11047d5e3432.png)

13
![image](https://cloud.githubusercontent.com/assets/14626151/11705990/587ee8b4-9eba-11e5-8a28-3b2d373ea96a.png)

14
![image](https://cloud.githubusercontent.com/assets/14626151/11705996/665ce1d4-9eba-11e5-83a8-a8a703983e35.png)

15
![image](https://cloud.githubusercontent.com/assets/14626151/11706002/76fa747a-9eba-11e5-8e2c-fcf6e3a4cfd5.png)

16
![image](https://cloud.githubusercontent.com/assets/14626151/11706016/851473da-9eba-11e5-8658-3a6e1f8fc0ad.png)

17
![image](https://cloud.githubusercontent.com/assets/14626151/11706017/93ca8f86-9eba-11e5-9e6e-7b0badece0bb.png)

18
![image](https://cloud.githubusercontent.com/assets/14626151/11706022/a1206fca-9eba-11e5-811a-71b0fd15e564.png)

19
![image](https://cloud.githubusercontent.com/assets/14626151/11706026/b0826e8c-9eba-11e5-9ba0-9c4e95040eb3.png)

20
![image](https://cloud.githubusercontent.com/assets/14626151/11706031/c0c56a2e-9eba-11e5-9991-03566de7180b.png)
